<OBJECT MONSTER-THUG
    (DESC "Thug")
    (COMBAT 3)
    (DEFENSE 6)
    (STAMINA 13)
    (FLAGS CONTBIT OPENBIT PERSONBIT)>

<OBJECT TWO-RATMEN
    (DESC "Two Ratmen")
    (COMBAT 6)
    (DEFENSE 9)
    (STAMINA 9)
    (FLAGS CONTBIT OPENBIT PERSONBIT PLURALBIT)>

<OBJECT TOMB-GUARDIAN
    (DESC "Tomb Guardian")
    (COMBAT 6)
    (DEFENSE 8)
    (STAMINA 12)
    (FLAGS CONTBIT OPENBIT PERSONBIT)>