#!/bin/bash

grep -n '(STORY' wartorn.zil | grep -v '(STORY TEXT' | grep -v '(STORY NONE)' | grep -v 'STORY-JUMP (STORY)' | grep -v '(STORY "'
grep -n '(CHOICE' wartorn.zil | grep -v '(CHOICES CHOICES' | grep -v '(CHOICES NONE)' | grep -v '(CHOICES YELLOWPORT-' | grep -v '(CHOICES MARLOCK-' | grep -v '(CHOICES "AUX"'
grep -n '(CONTINUE' wartorn.zil | grep -v '(CONTINUE STORY' | grep -v '(CONTINUE NONE)' | grep -v '(CONTINUE YELLOWPORT-'
grep -n '(DESTINATION' wartorn.zil | grep -v '(DESTINATIONS <LTABLE ' | grep -v '(DESTINATIONS NONE)' | grep -v '(DESTINATIONS YELLOWPORT-'| grep -v '(DESTINATIONS MARLOCK-' | grep -v '(DESTINATION NONE)'
grep -n '(REQUIREMENTS' wartorn.zil | grep -v '(REQUIREMENTS NONE)' | grep -v '(REQUIREMENTS <LTABLE ' | grep -v '(REQUIREMENTS STORY' | grep -v '(REQUIREMENTS YELLOWPORT-' | grep -v '(REQUIREMENTS MARLOCK-'
